

FROM ghcr.io/astral-sh/uv:python3.10-trixie-slim

USER root 

# Set working directory
WORKDIR /worker


# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc g++ libffi-dev python3-dev libssl-dev curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# Copy dependency files first to leverage cache
COPY pyproject.toml poetry.lock* ./

# Configure poetry to not use virtualenv
RUN uv pip install --system -r pyproject.toml

# Copy application source code

COPY celery_worker.py  .
COPY utils.py  .

ENV PYTHONPATH=/worker

RUN  groupadd -r celery && useradd -r -g celery celery && chown -R celery:celery /worker

USER celery

# Run Supervisor to manage FastAPI & Celery
CMD [ "celery", "-A", "celery_worker", "worker", "--loglevel=info" ]
